version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestEdge2Project
  gitServerName: test
  gitUrl: https://github.com/rlakshitha0912/TestEdge2Project
  gitUsername: rlakshitha0912
  gitBranch: main
- name: EdgeTestPackageCloudstreams
  version: "1.0"
  gitServerName: test
  gitUrl: https://github.com/rlakshitha0912
  gitUsername: rlakshitha0912
  gitBranch: main
- name: EdgeTestPackagesJDBC
  version: "1.0"
  gitServerName: test
  gitUrl: https://github.com/rlakshitha0912
  gitUsername: rlakshitha0912
  gitBranch: main
services:
- serviceName: project.testedge2.integrations:test
  packages:
  - name: TestEdge2Project
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.0.0.0.971
- serviceName: project.testedge2.integrations:date1
  packages:
  - name: TestEdge2Project
    version: "1.0"
  - name: EdgeTestPackageCloudstreams
    version: "1.0"
  - name: EdgeTestPackagesJDBC
    version: "1.0"
  - name: WmSalesforceProvider
    version: 10.7.0.0.53
