version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestEdge2Project
  gitServerName: test
  gitUrl: https://github.com/rlakshitha0912/TestEdge2Project
  gitUsername: rlakshitha0912
  gitBranch: main
